### ISSUE TITLE
please add readme/readme.txt

### ISSUE THREAD

**Issue by Alexey-T** [ThaiDat/cuda_transpose#4]
- basic descr of plugin, also mention that is should behave like (or almost like?) Sublime Text's command with the same name
- pls write there author name (or at least nickname) and Github URL of this page
- and 'license: MIT' line

**Comment by ThaiDat** [comment]
Added in [commit](https://github.com/ThaiDat/cuda_transpose/commit/72e3c3d96100037b907ac2ad023f89a4adc4ebfa)
