### ISSUE TITLE
this reame info is not clear

### ISSUE THREAD

**Issue by Alexey-T** [ThaiDat/cuda_transpose#6]
'Multiple carets: Do transpose on every single caret one by one' - what does it mean? that words under carets are moved? that lines are moved?

**Comment by ThaiDat** [comment]
It apply transpose command on each caret (swap two characters around each caret)

**Comment by Alexey-T** [comment]
Let's write this: 

Multiple carets without selections: For each caret, swap two chars around caret.

**Comment by ThaiDat** [comment]
Updated README. Tks
