### ISSUE TITLE
issues in install.inf

### ISSUE THREAD

**Issue by CudaText-addons** [ThaiDat/cuda_transpose#8]
1. 'swap 2 characters/lines' -> 'swap 2 characters'
2. `menu=o` moves the menu item into wrong menu - 'options / settings-plugins'. pls delete this line

**Comment by ThaiDat** [comment]
Sorry. Haven't notice that.
I think it also shouldn't appear under plugin menu as it is just a simple command. What should I do?

**Comment by CudaText-addons** [comment]
just del the line 'menu=o' and menuitem will be in Plugins. only there.

**Comment by CudaText-addons** [comment]
> it also shouldn't appear under plugin menu 

??? It must be there.

**Comment by ThaiDat** [comment]
Got it.
